services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network
        ports:
            - "5173:5173"
        environment:
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PORT: ${REDIS_PORT}
        depends_on:
            - db
            - redis

    webserver:
        image: nginx:stable-alpine
        container_name: laravel_nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./infrastructure/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - app-network

    db:
        image: postgres:15-alpine
        container_name: laravel_pgsql
        restart: always
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./infrastructure/pgdata:/var/lib/postgresql/data
        networks:
            - app-network

    redis:
        image: redis:7-alpine
        container_name: laravel_redis
        restart: always
        networks:
            - app-network

volumes:
    pgdata:

networks:
    app-network:
        driver: bridge
